
# Copyright (C) Igor Sysoev
# Copyright (C) Nginx, Inc.


all:
!if "$(OPENSSL_OUT_OF_TREE)" == "YES"

	if not exist $(OPENSSL_BUILD) mkdir $(OPENSSL_BUILD)
	cd $(OPENSSL_BUILD)

	perl "$(OPENSSL_SRC)\Configure" $(OPENSSL_TARGET) no-shared no-threads	\
		--prefix="%cd%\.openssl"				\
		--openssldir="%cd%\.openssl\ssl"			\
		--libdir=lib						\
		$(OPENSSL_OPT)

	$(MAKE)
	$(MAKE) install_sw

!else

	cd $(OPENSSL)

	perl Configure $(OPENSSL_TARGET) no-shared no-threads		\
		--prefix="%cd%/openssl" 				\
		--openssldir="%cd%/openssl/ssl" 			\
		$(OPENSSL_OPT)

	if exist ms\do_ms.bat (						\
		ms\do_ms						\
		&& $(MAKE) -f ms\nt.mak					\
		&& $(MAKE) -f ms\nt.mak install				\
	) else (							\
		$(MAKE)							\
		&& $(MAKE) install_sw					\
	)

!endif
