
# Copyright (C) Igor Sysoev
# Copyright (C) Nginx, Inc.


all:
!if "$(OPENSSL_OUT_OF_TREE)" == "YES"

	if not exist $(OPENSSL_BUILD) mkdir $(OPENSSL_BUILD)
	cd $(OPENSSL_BUILD)

	perl "$(OPENSSL_SRC)\Configure" BC-32 no-shared		\
		--prefix="%cd%\.openssl"			\
		--openssldir="%cd%\.openssl\ssl"		\
		--libdir=lib					\
		$(OPENSSL_OPT)

	$(MAKE)
	$(MAKE) install_sw

!else

	cd $(OPENSSL)

	perl Configure BC-32 no-shared --prefix=openssl $(OPENSSL_OPT)

	ms\do_nasm

	$(MAKE) -f ms\bcb.mak
	$(MAKE) -f ms\bcb.mak install

	# Borland's make does not expand "[ch]" in
	#    copy "inc32\openssl\*.[ch]" "openssl\include\openssl"
	copy inc32\openssl\*.h openssl\include\openssl

!endif
